pool:
  vmImage: 'vs2017-win2016'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'
  - script: |
      npm run lint
    displayName: 'Runs linting checks'

  - script: |
      npm test -- --coverage
    displayName: 'Runs tests'

  - script: |
      npm run build
    env:
      REACT_APP_CLIENT_ID: $(REACT_APP_CLIENT_ID)
    displayName: 'Build'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'coverage/clover.xml'
      reportDirectory: 'coverage'

  - task: DeleteFiles@1
    inputs:
      sourceFolder: '$(System.DefaultWorkingDirectory)/node_modules'
    displayName: 'Deleting node_modules'

  - task: FtpUpload@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    inputs:
      credentialsOption: 'inputs'
      serverUrl: $(FTP_ENDPOINT)
      username: $(FTP_USERNAME)
      password: $(FTP_PASSWORD)
      rootDirectory: '$(Build.SourcesDirectory)/build'
      filePatterns: '**'
      remoteDirectory: '/upload/$(Build.BuildId)/'
      #clean: false
      #cleanContents: false # Required when clean == False
      #preservePaths: false
      #trustSSL: false

  - task: AzureRmWebAppDeployment@3
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      azureSubscription: 'Graph-Explorer-ARM'
      WebAppName: 'graphTryIt'
      Package: '$(System.DefaultWorkingDirectory)'
      GenerateWebConfig: true
      WebConfigParameters: '-Handler iisnode -NodeStartFile server.js -appType node'
    displayName: 'Production deployment'

